global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'broker'
    static_configs:
      - targets: ['broker:7071']

  - job_name: 'consumer'
    static_configs:
      - targets: ['host.docker.internal:8000']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']