{
 "title": "Main dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Traffic control",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "clamp_min(delta(mobile_requests_total[1m]), 0)",
     "legendFormat": "Requests"
    },
    {
     "expr": "clamp_min(delta(all_signs_detected_total[1m]), 0)",
     "legendFormat": "Detected signs"
    },
    {
     "expr": "clamp_min(delta(signs_detected_total[1m]), 0)",
     "legendFormat": "Classified signs"
    }
   ]
  },
  {
   "title": "Server queue",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "delta(kafka_server_brokertopicmetrics_messagesin_total{topic=\"test-pictures-flutter\"}[$__interval])",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Classified signs",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sign_occurrences_total", "legendFormat": "{{class}}" }
   ]
  },
  {
   "title": "Detection locations",
   "type": "xychart",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "points_all", "legendFormat": "__auto" }
   ]
  }
 ]
}